export const metadata = {
  title: "restaurant -- menu",
  description: "Generated by create next app",
};

const layout = ({ children }: { children: React.ReactNode }) => {
  return <>{children}</>;
};

export default layout;
